fix icpx 2025.1 issue
One tests is using warning supressions because catch is using a compiler
option not supported before clang20. The workaround to disable this
warning is failing. By using `TEMPLATE_LIST_TEST_CASE` from catch
instead of `TEMPLATE_TEST_CASE` we can remove the workaround.

error wars:

```
unit/math/isSpecialIEEE.cpp:55:1: error: unknown warning group '-Wvariadic-macro-arguments-omitted', ignored [-Werror,-Wunknown-warning-option]
252
12:14:33
   55 | TEMPLATE_TEST_CASE("generic ieee helpers detect special values", "[math][generic][ieee]", float, double)
```